### ISSUE TITLE
What time resolution do we want the data?

### ISSUE THREAD

**Issue by tommylees112** [esowc/ml_drought#4]
Related: Issue [#3](https://github.com/esowc/ml_drought/issues/3)

Drought occurs over long time periods and is slowly evolving. Hourly data is probably too short. However monthly is too long.

It would be good to test timesteps: `3daily`, `weekly`, `10daily`, `bi-weekly` ...

The trade off:
`HOURLY`
- allows for resampling to any other time (upsample)
- we will want different time resolution eventually. Does making this first make sense?
- MUCH higher data volumes

`MONTHLY`
- easy to get started with the pipeline
- why not use the hourly to begin with because we know we will have to use this eventually

@gabrieltseng what do you think?

**Comment by gabrieltseng** [comment]
Committed to monthly - making this more flexible is a todo.
